spring:
  application:
    name: ticketpark
  jpa:
#    show-sql: true # SQL 쿼리 출력 활성화
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true


  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/TICKETPARK?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
      auth:
        database: 0 #토큰용
      queue:
        database: 1 #대기열용

jwt:
  secret: ${JWT_SECRET_KEY}
  # 토큰 만료 시간 (예: 1시간 = 3600000ms)
  access-expire-time: ${JWT_ACCESS_EXPIRE}
  refresh-expire-time: ${JWT_REFRESH_EXPIRE}
