spring:
  application:
    name: ticketpark
  jpa:
    show-sql: true # SQL 쿼리 출력 활성화
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        use_sql_comments: true # SQL 주석 추가

  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
#      password:
jwt:
  secret: ${JWT_SECRET_KEY}
  # 토큰 만료 시간 (예: 1시간 = 3600000ms)
  access-expire-time: ${JWT_ACCESS_EXPIRE}
  refresh-expire-time: ${JWT_REFRESH_EXPIRE}
